---
abstract: 'Just few modules I use, or like, or both.'
author:
  - 'Grzegorz Rożniecki <xaerxess@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-XAERXESS
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Code::TidyAll: 0
  Const::Fast: 0
  Dancer: 0
  Dancer2: 0
  Dist::Milla: 0
  Dist::Zilla: 5
  List::Gen: 0
  List::MoreUtils: 0
  Minilla: 0
  Moops: 0
  Plack: 1
  Smart::Match: 0
  Try::Tiny: 0
  experimental: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/Xaerxess/Task-BeLike-XAERXESS/issues
  homepage: https://github.com/Xaerxess/Task-BeLike-XAERXESS
  repository: https://github.com/Xaerxess/Task-BeLike-XAERXESS.git
version: 0.002
